name: normal_pr

on:
  push:
    branches: feature
    
  pull_request:
    types: [ready_for_review]
    
jobs:   
  check_pr_type:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3  
        
      - if: github.event_name == 'push'
        uses: 8BitJonny/gh-get-current-pr@2.1.1
        id: PR
        
      - 
        name: Check PR type
        if: github.event_name == 'push' && fromJSON(steps.PR.outputs.pr).draft != false 
        run: exit 1
        
  ACR_operations:
    runs-on: ubuntu-latest    
    needs: [check_pr_type]
    steps:     
      - 
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
  
      -
        name: Create new tag  
        uses: mathieudutour/github-tag-action@v6.0
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          append_to_pre_release_tag: RC
      
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ACR_ENDPOINT }}/request_app:${{steps.tag_version.outputs.new_tag}}
            
  Change_manifest_image:
    runs-on: ubuntu-latest     
    needs: [ACR_operations]
    
    steps:
      - 
        name: Check out other repo
        uses: actions/checkout@master
        with:
          repository: hakobmkoyan771/testingInfra
          path: ./
          token: ${{ secrets.GIT_TOKEN }}
           
      - 
        name: Clone application repo        
        run: |
          git clone --branch feature https://.:${{ secrets.GIT_TOKEN }}@github.com/Sahakanush/request_app
          
      -
        name: Get tag
        working-directory: request_app    
        run: |          
          echo "git_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      
      - 
        name: Change tag 
        working-directory: request_app/.github/
        run: |   
          pip install pyyaml  
          python3 change_tag.py ${{ secrets.ACR_USERNAME }}/request_app:${{env.git_tag}}
        
      -
        name: Push new image to GitHub
        working-directory: ./
        run: |
          git config --global user.name "sahakanush"
          git config --global user.email "sahakanush.terteryan2003@gmail.com"
          
          git add .
          git commit -m "Change Tag"
          git push
