name: normal_pr

on:
  push: 
    branches: feature       
    
  pull_request:
    types: [ready_for_review]
    
jobs:   
  Check_pr_type:    
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3  
        
      - 
        name: Get current PR info
        if: github.event_name == 'push'
        id: PR
        uses: 8BitJonny/gh-get-current-pr@2.1.1        
        
      - 
        name: Check PR type
        if: github.event_name == 'push' && fromJSON(steps.PR.outputs.pr).draft != false
        run: exit 1
        
  Tag_operations:
    runs-on: ubuntu-latest 
    needs: Check_pr_type
    
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}

    steps:            
      - 
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          
      -
        name: Create tag if event push
        if: github.event_name == 'push'
        uses: mathieudutour/github-tag-action@v6.0
        id: tag_version
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          append_to_pre_release_tag: RC
          tag_prefix: ''             
      - 
        if: github.event_name == 'push'
        run: echo "git_tag=${{steps.tag_version.outputs.new_version}}" >> $GITHUB_ENV
          
      -
        name: Create tag if event pull request
        if: github.event_name == 'pull_request'
        id: latest_tag
        uses: jimschubert/query-tag-action@v1        
      - 
        if: github.event_name == 'pull_request'
        run: echo "git_tag=${{steps.latest_tag.outputs.tag}}-RC.1" >> $GITHUB_ENV
        
      - 
        name: Get tag
        id: get_tag
        run: echo "::set-output name=tag::${{env.git_tag}}"
        
  ACR_operations:
    runs-on: ubuntu-latest    
    needs: Tag_operations
    steps:     
      - 
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - 
        name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - 
        name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{secrets.ACR_USERNAME}}/request_app:${{needs.Tag_operations.outputs.tag}}
            
  Change_manifest_image:
    runs-on: ubuntu-latest     
    needs: ACR_operations
    
    steps:
      - 
        name: Check out other repo
        uses: actions/checkout@master
        with:
          repository: armenmelkonyan90/devops_task_ArgoCD
          path: ./
          token: ${{ secrets.GIT_TOKEN }}
          
      - 
        name: Clone application repo        
        run: |
          git clone --branch feature https://.:${{ secrets.GIT_TOKEN }}@github.com/Sahakanush/request_app
           
      - 
        name: Change tag 
        working-directory: request_app/.github/
        run: |   
          pip install pyyaml  
          python3 change_tag.py ${{secrets.ACR_USERNAME}}/request_app:${{needs.Tag_operations.outputs.tag}}

      -
        name: Push new image to GitHub
        working-directory: ./
        run: |
          git config --global user.name "sahakanush"
          git config --global user.email "sahakanush.terteryan2003@gmail.com"
          
          git add .
          git commit -m "Channge Tag"
          git push
