name: normal_pr

on:
  push:
    branches: feature
    
  pull_request:
    types: [ready_for_review]
    
jobs:   
  check_pr_type:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3  
        
      - 
        uses: 8BitJonny/gh-get-current-pr@2.1.1
        id: PR
        
      - 
        name: Check PR type
        if: fromJSON(steps.PR.outputs.pr).draft != false 
        run: exit 1
        
  Get_tag:
    runs-on: ubuntu-latest 
    needs: [check_pr_type]
    
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
      
    steps:     
      - 
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          
      -
        id: latest_tag
        uses: jimschubert/query-tag-action@v1              
      
      - 
        if: github.event_name == 'pull_request'
        run: echo "::set-output name=tag::${{steps.latest_tag.outputs.tag}}"
        
      -
        name: Create new tag  
        if: github.event_name == 'push'
        uses: mathieudutour/github-tag-action@v6.0
        id: tag_version
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          append_to_pre_release_tag: RC
          tag_prefix: ''
          
      - 
        if: github.event_name == 'push'
        run: echo "::set-output name=tag::${{steps.tag_version.outputs.new_version}}"
        
  ACR_operations:
    runs-on: ubuntu-latest    
    needs: [Get_tag]
    steps:     
      - 
        run: echo "${{needs.Get_tag.outputs.tag}}"
      - 
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - 
        name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ACR_ENDPOINT }}/request_app:${{needs.Get_tag.outputs.tag}}
            
  Change_manifest_image:
    runs-on: ubuntu-latest     
    needs: [ACR_operations]
    
    steps:
      - 
        name: Check out other repo
        uses: actions/checkout@master
        with:
          repository: armenmelkonyan90/devops_task_ArgoCD
          path: ./
          token: ${{ secrets.GIT_TOKEN }}
           
      - 
        name: Change tag 
        working-directory: request_app/.github/
        run: |   
          pip install pyyaml  
          python3 change_tag.py ${{ secrets.ACR_USERNAME }}/request_app:${{needs.Get_tag.outputs.tag}}

      -
        name: Push new image to GitHub
        working-directory: ./
        run: |
          git config --global user.name "sahakanush"
          git config --global user.email "sahakanush.terteryan2003@gmail.com"
          
          git add .
          git commit -m "Channge Tag"
          git push
